#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 all:32:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          autofocus      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.2            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.2            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  03             \
    bottom_padding               03             \
    left_padding                 05             \
    right_padding                03             \
    window_gap                   05             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# window float settings
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Playdate Simulator$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Whisky$" manage=off
yabai -m rule --add app="^MediaMate$" manage=off

# jankyborders
borders style=round active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 hidpi=on &

echo "yabai & jankyborders configuration loaded.."
